modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="wantedboxable" #mandatory
version="${version}" #mandatory
displayName="Wanted Boxable" #mandatory
credits="IC2Classic Devs for IC2Classic" #optional
authors="CrossVas" #optional
description='''
I WANT IT BOXABLE!!!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.

[[dependencies.wantedboxable]]
modId="ic2"
mandatory=true
versionRange="[1.19.2-2.0.7,)"
ordering="AFTER"
side="BOTH"
